#pragma once


#define IDM_FILE_NEW	1
#define IDM_FILE_OPEN	2
#define IDM_FILE_SETTINGS	12
#define IDM_FILE_EXIT	3

#define IDM_EDIT_COPY	4
#define IDM_EDIT_PASTE	5
#define IDM_EDIT_CUT	6

#define IDM_EDIT_STATUSCHECK	7

#define IDM_EDIT_ONTOP 8

#define IDM_WINDOW_WIREFRAME 9
#define IDM_WINDOW_SHADED 10
#define IDM_WINDOW_TEXTURED 11

#define IDM_SETTINGS_ONE 13
#define IDM_SETTINGS_TWO 14
#define IDM_SETTINGS_THREE 15
#define IDM_SETTINGS_FOUR 16